### ISSUE TITLE
BoxTheJet aggregation missing files

### ISSUE THREAD

**Issue by Palomajol** [ramanakumars/SolarJets#31]
When running the scripts/do_aggregation.sh line for the aggregation some files seem to be missing. The extracting works and we see files for the question, shape and point. However, the reductions/ folder is empty except for question_reducer , the full error below

Extracting: 100% |#########################################################################################################################################################################################################################################################################################################################################| Time:  0:00:31
Broken libmagic installation detected. The python-magic module is installed but can't be imported. Please check that both python-magic and the libmagic shared library are installed correctly. Uploading media other than images may not work.
Traceback (most recent call last):
  File "/Users/pjol/Documents/SolarJets/BoxTheJets/scripts/normalize_subject_size.py", line 240, in <module>
    table = get_scales_set(save=True)
  File "/Users/pjol/Documents/SolarJets/BoxTheJets/scripts/normalize_subject_size.py", line 85, in get_scales_set
    subject_data = ascii.read('reductions/point_reducer_hdbscan_box_the_jets.csv')
  File "/Users/Shared/miniconda3/lib/python3.9/site-packages/astropy/io/ascii/ui.py", line 341, in read
    dat = _guess(table, new_kwargs, format, fast_reader)
  File "/Users/Shared/miniconda3/lib/python3.9/site-packages/astropy/io/ascii/ui.py", line 506, in _guess
    dat = reader.read(table)
  File "/Users/Shared/miniconda3/lib/python3.9/site-packages/astropy/io/ascii/core.py", line 1334, in read
    self.lines = self.inputter.get_lines(table, newline=newline)
  File "/Users/Shared/miniconda3/lib/python3.9/site-packages/astropy/io/ascii/core.py", line 329, in get_lines
    with get_readable_fileobj(table,
  File "/Users/Shared/miniconda3/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/Users/Shared/miniconda3/lib/python3.9/site-packages/astropy/utils/data.py", line 271, in get_readable_fileobj
    fileobj = io.FileIO(name_or_obj, 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'reductions/point_reducer_hdbscan_box_the_jets.csv'
Traceback (most recent call last):
  File "/Users/pjol/Documents/SolarJets/BoxTheJets/scripts/squash_frames.py", line 8, in <module>
    data = ascii.read(file, delimiter=',')
  File "/Users/Shared/miniconda3/lib/python3.9/site-packages/astropy/io/ascii/ui.py", line 341, in read
    dat = _guess(table, new_kwargs, format, fast_reader)
  File "/Users/Shared/miniconda3/lib/python3.9/site-packages/astropy/io/ascii/ui.py", line 506, in _guess
    dat = reader.read(table)
  File "/Users/Shared/miniconda3/lib/python3.9/site-packages/astropy/io/ascii/core.py", line 1334, in read
    self.lines = self.inputter.get_lines(table, newline=newline)
  File "/Users/Shared/miniconda3/lib/python3.9/site-packages/astropy/io/ascii/core.py", line 329, in get_lines
    with get_readable_fileobj(table,
  File "/Users/Shared/miniconda3/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/Users/Shared/miniconda3/lib/python3.9/site-packages/astropy/utils/data.py", line 271, in get_readable_fileobj
    fileobj = io.FileIO(name_or_obj, 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'extracts/point_extractor_by_frame_box_the_jets_scaled.csv'
usage: panoptes_aggregation reduce [-h] [-F {first,last,all}] [-O] [-c CPU_COUNT] [-d DIR] [-o OUTPUT] [-s] extracted_csv reducer_config
panoptes_aggregation reduce: error: argument extracted_csv: can't open '../extracts/point_extractor_by_frame_box_the_jets_scaled_squashed.csv': [Errno 2] No such file or directory: '../extracts/point_extractor_by_frame_box_the_jets_scaled_squashed.csv'
usage: panoptes_aggregation reduce [-h] [-F {first,last,all}] [-O] [-c CPU_COUNT] [-d DIR] [-o OUTPUT] [-s] extracted_csv reducer_config
panoptes_aggregation reduce: error: argument extracted_csv: can't open '../extracts/shape_extractor_rotateRectangle_box_the_jets_scaled_squashed.csv': [Errno 2] No such file or directory: '../extracts/shape_extractor_rotateRectangle_box_the_jets_scaled_squashed.csv'
Reducing: 100% |###########################################################################################################################################################################################################################################################################################################################################| Time:  0:00:12

**Comment by ramanakumars** [comment]
Changed the `normalize_subject_size.py` code to use the extractors to generate the list of subjects and fixing issues with multiprocessing.
